### PR TITLE
Try building with newer ffmpeg

### PR DESCRIPTION
**Pull request by hmaarrfk**
https://github.com/conda-forge/opencv-feedstock/issues/188#issuecomment-537324575
https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/294

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by jakirkham** [comment]
Is this still needed in light of PR ( https://github.com/conda-forge/av-feedstock/pull/20 )?

**Comment by hmaarrfk** [comment]
no

**Comment by jakirkham** [comment]
Thanks Mark!

**Pull request closed without merging**
