### PR TITLE
Bump version to 0.3.2

### PR DESCRIPTION
**Pull request by danielballan**
attn @caspervdw

### CODE REVIEW

**Comment by danielballan** [comment]
@pelson It looks like Travis is failing to find conda. Is this a widespread issue?

**Comment by caspervdw** [comment]
@danielballan Thanks for pushing this! The Appveyor build is currently not triggered. I am not sure but it might be that someone flicks some switch manually to re-enable the appveyor build.

A larger problem is the absence of a windows build of ffmpeg on conda-forge. Building ffmpeg is no trivial thing (especially on windows) and the Zeranoe binaries are already available over [here](https://ffmpeg.zeranoe.com/builds/).

We can either pull the binaries in at the conda-forge ffmpeg recipe (à la https://github.com/conda-forge/staged-recipes/issues/708) or pull them in (to build against) at the av recipe. In the latter case, the user should download the correct binary version and include its bin directory in the PATH variable him/herself.

**Comment by caspervdw** [comment]
Ref. https://github.com/conda-forge/ffmpeg-feedstock/pull/19

**Comment by danielballan** [comment]
Ah, for some reason I had in my head that conda-forge had already cracked FFmpeg Windows builds. I think the approach in #19 is sensible. Fingers crossed that appveyor passes. :- )

**Comment by caspervdw** [comment]
It should be available now on Windows! Apparently you have to regenerate the feedstock to enable appveyor using:

    conda-smithy regenerate

**Comment by caspervdw** [comment]
I just realized - the FFmpeg header files are missing so this windows build will still not work. Probably they are best included inside the FFmpeg package.

**Comment by caspervdw** [comment]
The headers will be included in the ffmpeg distribution soon. 

I am not sure if the unix-style `library` and `include` dirs are included by default. If not, just add the switch `--ffmpeg-dir=%LIBRARY_PREFIX%` to the `python setup.py install`.

**Comment by caspervdw** [comment]
@danielballan  Could you have a look at this PR? If you want, I can also make the PR that updates the feedstock in order to have Pyav on windows.

**Comment by danielballan** [comment]
Sure. It looks like Travis was failing before the actual build had even begun. I'll take a look....

**Pull request merged**
