### PR TITLE
Recompile with FFMPEG5

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #63.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Looking good! :)

**Comment by hmaarrfk** [comment]
Seems like there are about 25 feedstkcms. Should we just try to go to ffmpeg 5.0? I feel like it won't work just yet.

**Comment by h-vetinari** [comment]
> Seems like there are about 25 feedstocks. Should we just try to go to ffmpeg 5.0? I feel like it won't work just yet.

Sounds like it's few enough that we could go the openssl route and build both for ffmpeg 4 & 5, in case we stumble on a hard blocker for ffmpeg 5. WDYT?

**Comment by hmaarrfk** [comment]
yeah, i'm just trying to make sure we don't blow up the compile matrix. I guess it would be temporary.

I'm kinda tempted to go for it. fedora is on ffmpeg 5 and so is ubuntu. it is likely that we can find what we need from them: https://packages.ubuntu.com/kinetic/ffmpeg

We can likely find the patches we need and to learn from opencv and ffmpeg on that front.

**Pull request closed without merging**
